apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "patchmgmt.fullname" . }}-sources
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "patchmgmt.labels" . | nindent 4 }}
data:
  sources.txt: |
{{- if .Files.Get "sources.txt" }}
{{ .Files.Get "sources.txt" | indent 4 }}
{{- else }}
{{ printf "PLATFORM,NAMESPACE,RESOUCE_NAME,KIND\n" | indent 4 }}
{{- end }}


