{{- if .Values.api.env.databaseUrl }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "patchmgmt.fullname" . }}-db
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "patchmgmt.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.api.env.databaseUrl | quote }}
{{- end }}

{{- if .Values.api.env.twistlockUserPassword }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "patchmgmt.fullname" . }}-twistlock
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "patchmgmt.labels" . | nindent 4 }}
type: Opaque
stringData:
  TWISTLOCK_USER_PASSWORD: {{ .Values.api.env.twistlockUserPassword | quote }}
{{- end }}

{{- if .Values.api.env.backendAuthToken }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "patchmgmt.fullname" . }}-backend-auth
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "patchmgmt.labels" . | nindent 4 }}
type: Opaque
stringData:
  BACKEND_AUTH_TOKEN: {{ .Values.api.env.backendAuthToken | quote }}
{{- end }}

{{- if .Values.api.env.smtpPassword }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "patchmgmt.fullname" . }}-smtp
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "patchmgmt.labels" . | nindent 4 }}
type: Opaque
stringData:
  SMTP_PASSWORD: {{ .Values.api.env.smtpPassword | quote }}
{{- end }}

{{- if .Values.api.env.registrationToken }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "patchmgmt.fullname" . }}-registration
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "patchmgmt.labels" . | nindent 4 }}
type: Opaque
stringData:
  BACKEND_AUTH_TOKEN: {{ .Values.api.env.registrationToken | quote }}
{{- end }}

{{- if .Values.api.env.jwtSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "patchmgmt.fullname" . }}-jwt
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "patchmgmt.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.api.env.jwtSecret | quote }}
{{- end }}

