{{- if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "patchmgmt.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "patchmgmt.labels" . | nindent 4 }}
{{- end }}

